---
title: "Tool3"
output: html_document
---

```{r include=FALSE}

# clean Rs brain

rm(list=ls()) 

# load required packages

library(shiny)
library(shinydashboard)
library(openxlsx)
library(tidyverse)
library(ggpubr)
library(FactoMineR)
library(factoextra)
library(DT)

```

```{r}

# load data

performance_narrow <- read.xlsx(xlsxFile =here::here("data/performance_sum.xlsx"),sheet = 1) %>% 

                      gather(11:16,key = parameter,value = value,na.rm = TRUE)

```

```{r}

# use interface

ui <- dashboardPage(
  
  dashboardHeader(),
  
  dashboardSidebar(
    
    menuItem("Tool4",tabName = "Tool4")
  
    ),
 
   dashboardBody(
   
      # input tool 4
     
     tabItem(tabName = "Tool4",
             
             fluidRow(
               
               checkboxGroupInput(inputId = "Substrate_groups",label = "Substrate groups",choices = 
                                    
                                    levels(as.factor(performance_narrow$Diet_group)),selected = "Food waste"),
              
               checkboxGroupInput(inputId = "Performance_indicator",label = "Performance indicator"),
               
               plotOutput("Boxplot_substrate_groups"),
               
               dataTableOutput("Performance_indicator_summary")
                
             )
             )
   )

)
```

``` {r}

server <- function(input, output,session) { 
  
   observe({
     
     Performance_indicator_availability <- performance_narrow %>% filter(Diet_group  %in% input$Substrate_groups)
     
     updateCheckboxGroupInput(session, "Performance_indicator",
      label = "Performance indicator",
      choices = levels(as.factor(Performance_indicator_availability$parameter))
      # selected =  levels(as.factor(Performance_indicator_availability$parameter))
     )
   })
  
  
   performance_summary_narrow_subset <-
  
    reactive({
    
    # select Substrate groups based on input
    
      performance_narrow %>% 
  
      filter(Diet_group %in% input$Substrate_groups & parameter %in% input$Performance_indicator)
        
  })


   # calculate descriptive statistics
   
    performance_narrow_stats <- reactive({
   
     performance_summary_narrow_subset() %>% 
  
     group_by(Diet_group,parameter) %>% 
   
     summarise(n=n(),
            mean=round(mean(value,na.rm = TRUE),1),
            sd=round(mean(value,na.rm = TRUE),1),
            median=round(median(value,na.rm = TRUE),1),
            max=round(max(value,na.rm = TRUE),1),
            min=round(min(value,na.rm = TRUE),1))
      
    })
   
    
  # produce boxplot output based on manipulated data

    output$Boxplot_substrate_groups <- renderPlot({
     
      performance_summary_narrow_subset()  %>% 
  
      ggplot(aes(Diet_group,value)) +
  
      geom_boxplot() +
  
      geom_point() +
  
      labs(y = "% dm", x="", title = "Biowaste nutrients") +
  
      facet_wrap(~parameter) +
  
      coord_flip()
    })

    
   # produce summmary table 
    
    output$Performance_indicator_summary <- renderDT({performance_narrow_stats()})

}
      
   
```

```{r}
shinyApp(ui = ui,server = server)
```

